using CrestApps.Core.Models;
using Microsoft.Extensions.AI;

namespace CrestApps.Core.AI.Models;

/// <summary>
/// Represents a single chat prompt entry (user, assistant, or system message) stored within a session.
/// </summary>
public sealed class AIChatSessionPrompt : CatalogItem
{
    /// <summary>
    /// Gets or sets the session identifier this prompt belongs to.
    /// </summary>
    public string SessionId { get; set; }

    /// <summary>
    /// Gets or sets the role of the message author (User, Assistant, or System).
    /// </summary>
    public ChatRole Role { get; set; }

    /// <summary>
    /// Gets or sets the text content of this prompt message.
    /// </summary>
    public string Content { get; set; }

    /// <summary>
    /// Gets or sets the display title summarizing this prompt.
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this prompt was generated by the system rather than submitted by the user.
    /// </summary>
    public bool IsGeneratedPrompt { get; set; }

    /// <summary>
    /// Gets or sets the content-item identifiers of documents attached to this prompt.
    /// </summary>
    public IEnumerable<string> ContentItemIds { get; set; }

    /// <summary>
    /// Gets or sets the user's rating for the AI response associated with this prompt.
    /// <see langword="true"/> indicates a positive rating, <see langword="false"/> a negative rating, and <see langword="null"/> no rating.
    /// </summary>
    public bool? UserRating { get; set; }

    /// <summary>
    /// Gets or sets the document references returned with the AI response for this prompt, keyed by reference identifier.
    /// </summary>
    public Dictionary<string, AICompletionReference> References { get; set; }

    /// <summary>
    /// Gets or sets the UTC date and time when the prompt was created.
    /// </summary>
    public DateTime CreatedUtc { get; set; }
}
