namespace CrestApps.Core.AI.Models;

/// <summary>
/// Specifies the source strategy used to generate the title of an AI chat session.
/// </summary>
public enum AISessionTitleType
{
    /// <summary>
    /// The title is derived from the user's first prompt in the session.
    /// </summary>
    InitialPrompt,

    /// <summary>
    /// The title is generated by the AI model based on the conversation content.
    /// </summary>
    Generated,
}
